[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
fastbloom-rs = "=0.5.10"
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.143" }